// frontend.shop/src/components/BooksList.jsx
import React from 'react'
import axios from 'axios'
import NotificationSystem from 'react-notification-system'
import Select from 'react-select'
import 'react-select/dist/react-select.css';
import Pagination from './Pagination.jsx'
import FormFilter from './forms/FormFilter.jsx'
import * as config from '../config'
import {Link} from 'react-router-dom'

class BookItem extends React.Component
{
    constructor(props)
    {
        super(props);
        this.state = {
            data: this.props.data,
            _notificationSystem: null
        };
        this._addToCart = this._addToCart.bind(this);
        this._addNotification = this._addNotification.bind(this);
    }

    _addNotification(msg, level)
    {
        this.state._notificationSystem.addNotification({
            message: msg,
            level: level,
            position:  'tl'
        });
    }

    componentDidMount()
    {
        this.state._notificationSystem = this.refs.notificationSystem;
    }

    _addToCart()
    {
        window.sessionStorage.setItem(this.state.data.id, JSON.stringify(this.state.data));
        this._addNotification('Successfully added in cart', 'success');
    }

    render()
    {
        let { image, title, price, id } = this.props.data;
        return(
            <div className="row book-item">
                <NotificationSystem ref="notificationSystem" />
                <div className="col-md-4">
                    <img src={require(`../assets/img/${image}`)} width={100} height={100} />
                </div>
                <p>{title}</p>
                <strong className="price">{price}$</strong>
                <div className="row display-flex-end">
                    <Link className="btn btn-outline-primary" style={{marginRight: '10px'}} to={"/book/detail/" + id}>Detail</Link>
                    <button className="btn btn-outline-info" onClick={this._addToCart}>Add To Cart</button>
                </div>
            </div>
        );
    }
}

export default class BooksList extends React.Component
{
    constructor(props)
    {
        super(props);
        this.state = {
            data: [],
            pageOfItems: [],
            title: ''
        };
        this.onChangePage = this.onChangePage.bind(this);
        this._onChange = this._onChange.bind(this);
        this._onSubmit = this._onSubmit.bind(this);
    }

    componentDidMount()
    {
        axios.get(config.API_BOOKS)
            .then((data) => {
                this.setState({ data: data.data.response });
            }).catch((err) => {
                console.log(err);
            });
    }

    _onChange(e)
    {
        this.setState({ title: e.target.value });
    }

    _onSubmit(e)
    {
        e.preventDefault();
        axios.post(config.API_BOOK_SEARCH, {title: this.state.title})
             .then((data) => {
                 this.setState({ data: data.data.response });
             }).catch((err) => {
                 console.log(err);
             });
    }

    onChangePage(pageOfItems) {
        // update state with new page of items
        this.setState({ pageOfItems: pageOfItems });
    }

    render()
    {
        let items = [];
        this.state.pageOfItems.map((item) => {
                items.push(
                    <div className="col-md-5">
                        <BookItem data={item} />
                    </div>
                );
        });
        return(
            <div className="row clearfix">
                <FormFilter onChange={this._onChange}
                        onSubmit={this._onSubmit}/>
                {items}
                <div className="row margin-top-30">
                    <Pagination items={this.state.data} onChangePage={this.onChangePage}/>
                </div>
            </div>
        );
    }
}

// frontend.shop.admin/src/components/BooksList.vue
<template>
    <div class="row">
        <div class="container">
            <b-table striped hover
                     :items="books"
                     :fields="fields"
                     :current-page="currentPage"
                     :per-page="perPage"
                     :filter="filter"
                     @filtered="onFiltered"
            >
                <template slot="Image" slot-scope="data">
                    <img :src="require(`../assets/images/${data.item.image}`)" width="50" height="50" />
                </template>
                <template slot="Delete" slot-scope="data">
                    <button class="btn btn-outline-danger" @click="deleteBook(data.item.id)">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </template>
                <template slot="Edit" slot-scope="data">
                    <router-link v-bind:to="`admin/book/edit/${data.item.id}`" class="btn btn-outline-primary"><i class="fas fa-pencil-alt"></i></router-link>
                </template>
                <template slot="Detail" slot-scope="data">
                    <router-link title="Detail" v-bind:to="`admin/book/detail/${data.item.id}`" class="btn btn-outline-primary"><i class="fas fa-eye"></i></router-link>
                </template>
            </b-table>
            <div class="row" style="display: flex; justify-content: flex-end">
                <b-pagination :total-rows="totalRows" :per-page="perPage" v-model="currentPage" class="" />
            </div>
        </div>
    </div>
</template>

<script>
    import axios from 'axios'
    import * as config from '../config'
    import VueBootstrapTable from 'vue2-bootstrap-table2'
    export default {
        components:{
            'vue-bootstrap-table': VueBootstrapTable
        },
        data(){
            return{
                books: [],
                filter: null,
                currentPage: 1,
                perPage: 5,
                totalRows: 0,
                fields: [
                    {
                        key: 'Image',
                        label: ''
                    },
                    {
                        key: 'title',
                        label: 'Title'
                    },
                    {
                        key: 'author',
                        label: 'Author'
                    },
                    {
                        key: 'pages',
                        label: 'Pages'
                    },
                    {
                        key: 'price',
                        label: 'Price $'
                    },
                    {
                        key: 'Delete',
                        label: ''
                    },
                    {
                        key: 'Edit',
                        label: ''
                    },
                    {
                        key: 'Detail',
                        label: ''
                    },
                ]
            }
        },
        mounted(){
            axios.get(config.API_ADMIN_BOOKS)
                .then((data) => {
                    this.books = data.data.response;
                }).catch((err) => {
                   console.log(err);
                })
        },
        methods: {
            notify(text, type){
                this.$notify({
                    group: 'example',
                    text: text,
                    type: type
                });
            },
            deleteBook(id)
            {
                axios.get(config.API_ADMIN_BOOK_DELETE + id)
                    .then((data) => {
                        this.notify('Successfully deleted!', 'success');
                        setTimeout(() => {
                            location.replace('/');
                        }, 1000);
                    }).catch((err) => {

                });
            },
            onFiltered (filteredItems) {
                this.totalRows = filteredItems.length;
                this.currentPage = 1;
            }
        }
    }
</script>

<style scoped>

</style>
