// frontend.blog.admin/src/components/Head.vue
<template>
    <div class="container">
         <nav class="row menu">
             <ul>
                 <li><a href="/">Main</a></li>
                 <li><a href="#/admin/comments">Comments</a></li>
                 <li><a href="#/admin/blog/add">Add new blog</a></li>
             </ul>
         </nav>
    </div>
</template>

<script>
    export default {

    }
</script>

<style lang="stylus" scoped>

</style>

// frontend.shop.admin/src/components/Head.jsx
import React from 'react'
import {Link} from 'react-router'

export default class Head extends React.Component
{
    constructor(props)
    {
        super(props);
    }

    render()
    {
        return(
            <div className="container">
                <nav className="row menu">
                    <ul>
                        <li><a href="/">Main</a></li>
                        <li><a href="/admin/book/add">Add book</a></li>
                    </ul>
                </nav>
            </div>
        );
    }
}
