// frontend.shop.admin/src/components/Head.jsx
import React from 'react'
import {Link} from 'react-router'

export default class Head extends React.Component
{
    constructor(props)
    {
        super(props);
    }

    render()
    {
        return(
            <div className="container">
                <nav className="row menu">
                    <ul>
                        <li><a href="/">Main</a></li>
                        <li><a href="/admin/book/add">Add book</a></li>
                    </ul>
                </nav>
            </div>
        );
    }
}

// frontend.shop.admin/src/components/Head.vue
<template>
    <div class="container">
         <nav class="row menu">
             <ul>
                 <li><a href="/">Main</a></li>
                 <li><a href="#/admin/book/add">Add book</a></li>
                 <li><a href="#/admin/orders">Orders</a></li>
             </ul>
         </nav>
    </div>
</template>

<script>
    export default {

    }
</script>

<style scoped>

</style>
