// frontend.shop/src/components/forms/CommentForm.jsx
import React from 'react'
import TextField from '../TextField.jsx';
import axios from 'axios'
import * as config from '../../config'

export default class CommentForm extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            error: {
                name: '',
                email: '',
                comment: ''
            }
        };
        this._onSubmit = this._onSubmit.bind(this);
        this._onChange = this._onChange.bind(this);
    }

    _onSubmit(e) {
        e.preventDefault();
        let book = this.state;
        book.book_id = this.props.book_id;
        axios.post(config.API_BOOK_COMMENT_ADD, {
            name: book.name,
            email: book.email,
            comment: book.comment,
            book_id: book.book_id
        }).then(data => {
            setTimeout(() => {
                location.reload();
            }, 1000);
        }).catch(err => {
            console.log(err);
        });
    }

    _onChange(e) {
        let {name, value} = e.target;
        this.setState({ [name]: value });
    }

    render() {
        return(
            <div className="row">
                <div className="container display-flex">
                    <form action="" methods="POST" className="col-md-7" onSubmit={this._onSubmit}>
                        <div className="col-md-4">
                            <TextField
                                type="text"
                                name="name"
                                onChange={this._onChange}
                                placeholder="Name"
                                required
                            />
                        </div>
                        <div className="col-md-4">
                            <TextField
                                type="email"
                                name="email"
                                onChange={this._onChange}
                                placeholder="Email"
                                required
                            />
                        </div>
                        <div className="col-md-4">
                            <textarea name="comment"
                                      onChange={this._onChange}
                                      required>
                            </textarea>
                        </div>
                        <div className="col-md-1">
                            <button type="submit" className="btn btn-outline-success">Add comment</button>
                        </div>
                    </form>
                </div>
            </div>
        );
    }
}

// frontend.blog/src/components/CommentForm.vue
<template>
    <div class="row padd-top-30">
         <form method="post" action="" @submit.prevent="onSubmit" class="col-md-8 offset-md-4">
              <div class="col-md-4">
                  <b-form-input v-model="comment.name"
                                type="text"
                                placeholder="Name"
                                required></b-form-input>
              </div>
              <div class="col-md-4 margin-top-15">
                  <b-form-input v-model="comment.email"
                                type="email"
                                placeholder="Email"
                                required></b-form-input>
              </div>
              <div class="col-md-4 margin-top-15">
                  <b-form-textarea
                          v-model="comment.body"
                          placeholder="Comments..."
                          :rows="3"
                          :max-rows="6"
                          required
                  >
                  </b-form-textarea>
              </div>
             <div class="row offset-md-1 margin-top-15">
                 <button type="submit" class="btn btn-outline-success">
                     Add comment
                 </button>
             </div>
         </form>
    </div>
</template>

<script>
    import axios from 'axios';
    import * as config from '../config';
    export default {
        props: {
           id: {type: Number, required: true}
        },
        data(){
            return {
                comment: {
                    name: '',
                    email: '',
                    body: ''
                }
            }
        },
        methods: {
            onSubmit(e) {
                e.preventDefault();
                let { name, email, body } = this.comment;
                console.log({
                    name: name,
                    email: email,
                    body: body,
                    blog_id: id
                });
                // axios.post(config.API_COMMENT_ADD, {
                //      name: name,
                //      email: email,
                //      body: body,
                //      blog_id: id
                // }).then(data => { location.reload(); })
                //     .catch(err => {});
            }
        }
    }
</script>

<style lang="stylus" scoped>
    .padd-top-30
        padding-top 30px
    .margin-top-15
        margin-top 15px
</style>
